#census API key
api_key = "839fc96162a9e16e7896434e7592eccaf7938706"

#CDC app token
app_token = "aBj1zOdJs530ivzSUlyOHkLaf"

var_dict = {
    "dhc": {
        "url": "https://api.census.gov/data/2020/dec/dhc",
        "vars": {
            # total
            "P12_001N": {
                "long_name": "!!Total:",
                "short_name": "total_population",
            },
            # male and female totals
            "P12_002N": {
                "long_name": "!!Total:!!Male:: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "total_male",
            },
            "P12_026N": {
                "long_name": "!!Total:!!Female:: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "total_female",
            },
            # male by age category
            "P12_003N": {
                "long_name": "!!Total:!!Male:!!Under 5 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_under_5",
            },
            "P12_004N": {
                "long_name": "!!Total:!!Male:!!5 to 9 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_5_to_9",
            },
            "P12_005N": {
                "long_name": "!!Total:!!Male:!!10 to 14 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_10_to_14",
            },
            "P12_006N": {
                "long_name": "!!Total:!!Male:!!15 to 17 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_15_to_17",
            },
            "P12_020N": {
                "long_name": "!!Total:!!Male:!!65 and 66 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_65_to_66",
            },
            "P12_021N": {
                "long_name": "!!Total:!!Male:!!67 to 69 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_67_to_69",
            },
            "P12_022N": {
                "long_name": "!!Total:!!Male:!!70 to 74 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_70_to_74",
            },
            "P12_023N": {
                "long_name": "!!Total:!!Male:!!75 to 79 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_75_to_79",
            },
            "P12_024N": {
                "long_name": "!!Total:!!Male:!!80 to 84 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_80_to_84",
            },
            "P12_025N": {
                "long_name": "!!Total:!!Male:!!85 years and over: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "m_85_plus",
            },
            # female by age category
            "P12_027N": {
                "long_name": "!!Total:!!Female:!!Under 5 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_under_5",
            },
            "P12_028N": {
                "long_name": "!!Total:!!Female:!!5 to 9 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_5_to_9",
            },
            "P12_029N": {
                "long_name": "!!Total:!!Female:!!10 to 14 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_10_to_14",
            },
            "P12_030N": {
                "long_name": "!!Total:!!Female:!!15 to 17 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_15_to_17",
            },
            "P12_044N": {
                "long_name": "!!Total:!!Female:!!65 and 66 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_65_to_66",
            },
            "P12_045N": {
                "long_name": "!!Total:!!Female:!!67 to 69 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_67_to_69",
            },
            "P12_046N": {
                "long_name": "!!Total:!!Female:!!70 to 74 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_70_to_74",
            },
            "P12_047N": {
                "long_name": "!!Total:!!Female:!!75 to 79 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_75_to_79",
            },
            "P12_048N": {
                "long_name": "!!Total:!!Female:!!80 to 84 years: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_80_to_84",
            },
            "P12_049N": {
                "long_name": "!!Total:!!Female:!!85 years and over: SEX BY AGE FOR SELECTED AGE CATEGORIES",
                "short_name": "f_85_plus",
            },
        },
    },
    "acs5": {
        "url": "https://api.census.gov/data/2020/acs/acs5/subject",# note that if any variable not found in a "subject" table is used, this base URL will need to be re-configured!
        "vars": {
            "S1810_C03_001E": {
                "long_name": "Percent with a disability!!Estimate!!Total civilian noninstitutionalized population",
                "short_name": "pct_w_disability",
            },
            "S1810_C03_001M": {
                "long_name": "Margin of Error!!Percent with a disability!!Total civilian noninstitutionalized population",
                "short_name": "moe_pct_w_disability",
            },
            "S2701_C03_001E": {
                "long_name": "Estimate!!Percent Insured!!Civilian noninstitutionalized population",
                "short_name": "pct_insured",
            },
            "S2701_C03_001M": {
                "long_name": "Margin of Error!!Percent Insured!!Civilian noninstitutionalized population	",
                "short_name": "moe_pct_insured",
            },
            "S2701_C05_001E": {
                "long_name": "Estimate!!Percent Uninsured!!Civilian noninstitutionalized population",
                "short_name": "pct_uninsured",
            },
            "S2701_C05_001M": {
                "long_name": "Margin of Error!!Percent Uninsured!!Civilian noninstitutionalized population	",
                "short_name": "moe_pct_uninsured",
            },
        },
    },
    "cdc": {
        "PLACES":{
            "url":{
                "county":"https://data.cdc.gov/resource/swc5-untb.json",
                "place":"https://data.cdc.gov/resource/eav7-hnsx.json",
                "zcta":"https://data.cdc.gov/resource/qnzd-25i4.json",
                "tract":"https://data.cdc.gov/resource/cwsq-ngmh.json",
            },
            "vars": {
                "CASTHMA": {
                    "long_name": "Current asthma among adults aged >=18 years",
                    "short_name": "pct_asthma",
                    "data_value_type_name": "crude prevalence",
                    "data_value_type_id": "CrdPrv",
                },
                "COPD": {
                    "long_name": "Chronic obstructive pulmonary disease among adults aged >=18 years",
                    "short_name": "pct_copd",
                    "data_value_type_name": "crude prevalence",
                    "data_value_type_id": "CrdPrv",
                },
                "CHD": {
                    "long_name": "Coronary heart disease among adults aged >=18 years",
                    "short_name": "pct_hd",
                    "data_value_type_name": "crude prevalence",
                    "data_value_type_id": "CrdPrv",
                },
                "STROKE": {
                    "long_name": "Stroke among adults aged >=18 years",
                    "short_name": "pct_stroke",
                    "data_value_type_name": "crude prevalence",
                    "data_value_type_id": "CrdPrv",
                },
                "DIABETES": {
                    "long_name": "Diagnosed diabetes among adults aged >=18 years",
                    "short_name": "pct_diabetes",
                    "data_value_type_name": "crude prevalence",
                    "data_value_type_id": "CrdPrv",
                },
                "KIDNEY": {
                    "long_name": "Chronic kidney disease among adults aged >=18 years",
                    "short_name": "pct_kd",
                    "data_value_type_name": "crude prevalence",
                    "data_value_type_id": "CrdPrv",
                },
            },
        },
        "SDOH":{
            "url":{
                "county":"https://data.cdc.gov/resource/i6u4-y3g4.json",
                "place":"https://data.cdc.gov/resource/edkk-ze78.json",
                "zcta":"https://data.cdc.gov/resource/bumh-rgsq.json",
                "tract":"https://data.cdc.gov/resource/e539-uadk.json",
            },
            "vars": {
                "REMNRTY": {
                    "long_name": "Persons of racial or ethnic minority status",
                    "short_name": "pct_minority",
                },
                "NOHSDP": {
                    "long_name": "No high school diploma among adults aged 25 years or older",
                    "short_name": "pct_no_hsdiploma",
                },
                "POV150": {
                    "long_name": "Persons living below 150% of the poverty level",
                    "short_name": "pct_below_150pov",
                },
                "BROAD": {
                    "long_name": "No broadband internet subscription among households",
                    "short_name": "pct_no_bband",
                },
            },
        },
    },
}

comment_dict = {'BORO1': '',
 'BORO19': '',
 'AK15': 'Data represent information from nearest county (Anchorage Municipality), which includes Municipality of Anchorage and Anchorage.',
 'CENS9': '',
 'BORO17': '',
 'CENS11': '',
 'CENS10': '',
 'BORO18': '',
 'CENS3': '',
 'BORO8': '',
 'AK124': 'Data represent information from nearest county (Fairbanks North Star Borough), which includes Fairbanks North Star Borough and Fairbanks.',
 'BORO16': '',
 'CENS4': '',
 'BORO9': '',
 'AK172': 'Data represent information from nearest county (Juneau City and Borough), which includes City and Borough of Juneau, Juneau, Lena Beach, Auke Bay, Tee Harbor, Thane, and Douglas.',
 'AK225': 'Data represent information from nearest county (Juneau City and Borough), which includes City and Borough of Juneau, Juneau, Lena Beach, Auke Bay, Tee Harbor, Thane, and Douglas.',
 'AK27': 'Data represent information from nearest county (Juneau City and Borough), which includes City and Borough of Juneau, Juneau, Lena Beach, Auke Bay, Tee Harbor, Thane, and Douglas.',
 'AK388': 'Data represent information from nearest county (Juneau City and Borough), which includes City and Borough of Juneau, Juneau, Lena Beach, Auke Bay, Tee Harbor, Thane, and Douglas.',
 'AK395': 'Data represent information from nearest county (Juneau City and Borough), which includes City and Borough of Juneau, Juneau, Lena Beach, Auke Bay, Tee Harbor, Thane, and Douglas.',
 'AK99': 'Data represent information from nearest county (Juneau City and Borough), which includes City and Borough of Juneau, Juneau, Lena Beach, Auke Bay, Tee Harbor, Thane, and Douglas.',
 'BORO15': '',
 'BORO7': '',
 'BORO4': '',
 'CENS5': '',
 'BORO2': '',
 'BORO13': '',
 'CENS6': '',
 'BORO3': '',
 'BORO6': '',
 'BORO11': '',
 'CENS7': '',
 'BORO10': '',
 'AK29': 'Data represent information from nearest county (Sitka City and Borough), which includes City and Borough of Sitka, Baranof Warm Springs, Sitka, and Chatham.',
 'AK360': 'Data represent information from nearest county (Sitka City and Borough), which includes City and Borough of Sitka, Baranof Warm Springs, Sitka, and Chatham.',
 'AK60': 'Data represent information from nearest county (Sitka City and Borough), which includes City and Borough of Sitka, Baranof Warm Springs, Sitka, and Chatham.',
 'BORO5': '',
 'CENS2': '',
 'BORO12': '',
 'AK249': 'Data represent information from nearest county (Wrangell City and Borough), which includes City and Borough of Wrangell, Meyers Chuck, and Wrangell.',
 'AK434': 'Data represent information from nearest county (Wrangell City and Borough), which includes City and Borough of Wrangell, Meyers Chuck, and Wrangell.',
 'BORO14': '',
 'AK53': 'Data represent information from nearest county (Yakutat City and Borough), which includes City and Borough of Yakutat and Cape Yakataga.',
 'CENS8': '',
 'AK110': 'Data represent information from nearest county (Yakutat City and Borough), which includes City and Borough of Yakutat and Cape Yakataga.',
 'AK43': 'Data represent information from nearest county (Yakutat City and Borough), which includes City and Borough of Yakutat and Cape Yakataga.',
 'AK103': 'Data for this place represent multiple merged census tracts: Census Tract 2.01, Census Tract 2.02, Census Tract 2.04, Census Tract 2.05, and Census Tract 2.06',
 'AK136': 'Data for this place represent multiple merged census tracts: Census Tract 2.01, Census Tract 2.02, Census Tract 2.04, Census Tract 2.05, and Census Tract 2.06',
 'AK166': 'Data for this place represent multiple merged census tracts: Census Tract 2.01, Census Tract 2.02, Census Tract 2.04, Census Tract 2.05, and Census Tract 2.06',
 'AK328': 'Data for this place represent multiple merged census tracts: Census Tract 2.01, Census Tract 2.02, Census Tract 2.04, Census Tract 2.05, and Census Tract 2.06',
 'AK333': 'Data for this place represent multiple merged census tracts: Census Tract 2.01, Census Tract 2.02, Census Tract 2.04, Census Tract 2.05, and Census Tract 2.06',
 'AK44': 'Data for this place represent multiple merged census tracts: Census Tract 2.01, Census Tract 2.02, Census Tract 2.04, Census Tract 2.05, and Census Tract 2.06',
 'AK439': 'Data for this place represent multiple merged census tracts: Census Tract 9801 and Census Tract 9802',
 'AK438': 'Data for this place represent multiple merged census tracts: Census Tract 9801 and Census Tract 9802',
 'AK2': 'Data represent information from nearest incorporated place (Akhiok city), which includes Akhiok.',
 'AK3': 'Data represent information from nearest census designated place (Akiachak CDP), which includes Akiachak.',
 'AK4': 'Data represent information from nearest incorporated place (Akiak city), which includes Akiak.',
 'AK5': 'Data represent information from nearest incorporated place (Akutan city), which includes Akutan.',
 'AK6': 'Data represent information from nearest incorporated place (Alakanuk city), which includes Alakanuk.',
 'AK7': 'Data represent information from nearest census designated place (Alatna CDP), which includes Alatna.',
 'AK488': 'Data represent information from nearest census designated place (Alcan Border CDP), which includes Alcan Border.',
 'AK8': 'Data represent information from nearest incorporated place (Aleknagik city), which includes Aleknagik.',
 'AK1': 'Data represent information from nearest census designated place (Aleneva CDP), which includes Afognak and Aleneva.',
 'AK489': 'Data represent information from nearest census designated place (Aleneva CDP), which includes Afognak and Aleneva.',
 'AK11': 'Data represent information from nearest incorporated place (Allakaket city), which includes Allakaket.',
 'AK12': 'Data represent information from nearest incorporated place (Ambler city), which includes Ambler.',
 'AK13': 'Data represent information from nearest incorporated place (Anaktuvuk Pass city), which includes Anaktuvuk Pass.',
 'AK14': 'Data represent information from nearest census designated place (Anchor Point CDP), which includes Anchor Point.',
 'AK16': 'Data represent information from nearest incorporated place (Anderson city), which includes Anderson and Clear.',
 'AK81': 'Data represent information from nearest incorporated place (Anderson city), which includes Anderson and Clear.',
 'AK18': 'Data represent information from nearest incorporated place (Angoon city), which includes Angoon.',
 'AK19': 'Data represent information from nearest incorporated place (Aniak city), which includes Aniak.',
 'AK21': 'Data represent information from nearest incorporated place (Anvik city), which includes Anvik.',
 'AK22': 'Data represent information from nearest census designated place (Arctic Village CDP), which includes Arctic Village.',
 'AK23': 'Data represent information from nearest incorporated place (Atka city), which includes Atka.',
 'AK24': 'Data represent information from nearest census designated place (Atmautluak CDP), which includes Atmautluak.',
 'AK25': 'Data represent information from nearest incorporated place (Atqasuk city), which includes Atqasuk.',
 'AK26': 'Data represent information from nearest census designated place (Attu Station CDP), which includes Attu.',
 'AK490': 'Data represent information from nearest census designated place (Badger CDP), which includes Badger.',
 'AK491': 'Data represent information from nearest census designated place (Bear Creek CDP), which includes Bear Creek.',
 'AK31': 'Data represent information from nearest census designated place (Beaver CDP), which includes Beaver.',
 'AK492': 'Data represent information from nearest census designated place (Beluga CDP), which includes Beluga.',
 'AK36': 'Data represent information from nearest incorporated place (Bethel city), which includes Bethel.',
 'AK37': 'Data represent information from nearest incorporated place (Bettles city), which includes Bettles.',
 'AK38': 'Data represent information from nearest census designated place (Big Delta CDP), which includes Big Delta.',
 'AK39': 'Data represent information from nearest census designated place (Big Lake CDP), which includes Big Lake.',
 'AK42': 'Data represent information from nearest census designated place (Birch Creek CDP), which includes Birch Creek.',
 'AK47': 'Data represent information from nearest incorporated place (Brevig Mission city), which includes Brevig Mission.',
 'AK48': 'Data represent information from nearest incorporated place (Buckland city), which includes Buckland.',
 'AK493': 'Data represent information from nearest census designated place (Buffalo Soapstone CDP), which includes Buffalo Soapstone.',
 'AK45': 'Data represent information from nearest census designated place (Butte CDP), which includes Bodenburg Butte and Butte.',
 'AK494': 'Data represent information from nearest census designated place (Butte CDP), which includes Bodenburg Butte and Butte.',
 'AK50': 'Data represent information from nearest census designated place (Cantwell CDP), which includes Cantwell.',
 'AK54': 'Data represent information from nearest census designated place (Central CDP), which includes Central and Circle Hot Springs.',
 'AK78': 'Data represent information from nearest census designated place (Central CDP), which includes Central and Circle Hot Springs.',
 'AK57': 'Data represent information from nearest census designated place (Chalkyitsik CDP), which includes Chalkyitsik.',
 'AK495': 'Data represent information from nearest census designated place (Chase CDP), which includes Chase.',
 'AK61': 'Data represent information from nearest incorporated place (Chefornak city), which includes Chefornak.',
 'AK496': 'Data represent information from nearest census designated place (Chena Ridge CDP), which includes Chena Ridge.',
 'AK321': 'Data represent information from nearest census designated place (Chenega CDP), which includes Port Ashton and Chenega Bay.',
 'AK63': 'Data represent information from nearest census designated place (Chenega CDP), which includes Port Ashton and Chenega Bay.',
 'AK64': 'Data represent information from nearest incorporated place (Chevak city), which includes Chevak.',
 'AK65': 'Data represent information from nearest census designated place (Chickaloon CDP), which includes Chickaloon.',
 'AK66': 'Data represent information from nearest census designated place (Chicken CDP), which includes Chicken.',
 'AK68': 'Data represent information from nearest census designated place (Chignik Lagoon CDP), which includes Chignik Lagoon.',
 'AK69': 'Data represent information from nearest census designated place (Chignik Lake CDP), which includes Chignik Lake.',
 'AK70': 'Data represent information from nearest census designated place (Chiniak CDP), which includes Chiniak.',
 'AK71': 'Data represent information from nearest census designated place (Chisana CDP), which includes Chisana.',
 'AK167': 'Data represent information from nearest census designated place (Chistochina CDP), which includes Indian River and Chistochina.',
 'AK72': 'Data represent information from nearest census designated place (Chistochina CDP), which includes Indian River and Chistochina.',
 'AK73': 'Data represent information from nearest census designated place (Chitina CDP), which includes Chitina.',
 'AK75': 'Data represent information from nearest incorporated place (Chuathbaluk city), which includes Chuathbaluk.',
 'AK77': 'Data represent information from nearest census designated place (Circle CDP), which includes Circle.',
 'AK79': 'Data represent information from nearest census designated place (Clam Gulch CDP), which includes Clam Gulch.',
 'AK80': "Data represent information from nearest incorporated place (Clark's Point city), which includes Clark's Point.",
 'AK83': 'Data represent information from nearest incorporated place (Coffman Cove city), which includes Coffman Cove.',
 'AK84': 'Data represent information from nearest census designated place (Cohoe CDP), which includes Cohoe.',
 'AK85': 'Data represent information from nearest incorporated place (Cold Bay city), which includes Cold Bay.',
 'AK497': 'Data represent information from nearest census designated place (Coldfoot CDP), which includes Coldfoot.',
 'AK86': 'Data represent information from nearest census designated place (College CDP), which includes College.',
 'AK87': 'Data represent information from nearest census designated place (Cooper Landing CDP), which includes Cooper Landing.',
 'AK88': 'Data represent information from nearest census designated place (Copper Center CDP), which includes Copper Center.',
 'AK123': 'Data represent information from nearest incorporated place (Cordova city), which includes Eyak and Cordova.',
 'AK89': 'Data represent information from nearest incorporated place (Cordova city), which includes Eyak and Cordova.',
 'AK498': 'Data represent information from nearest census designated place (Covenant Life CDP), which includes Covenant Life.',
 'AK92': 'Data represent information from nearest census designated place (Crooked Creek CDP), which includes Crooked Creek.',
 'AK499': 'Data represent information from nearest census designated place (Crown Point CDP), which includes Crown Point.',
 'AK94': 'Data represent information from nearest incorporated place (Deering city), which includes Deering.',
 'AK95': 'Data represent information from nearest incorporated place (Delta Junction city), which includes Delta Junction.',
 'AK500': 'Data represent information from nearest census designated place (Deltana CDP), which includes Deltana.',
 'AK501': 'Data represent information from nearest census designated place (Denali Park CDP), which includes Denali Park.',
 'AK502': 'Data represent information from nearest census designated place (Diamond Ridge CDP), which includes Diamond Ridge.',
 'AK180': 'Data represent information from nearest incorporated place (Dillingham city), which includes Kanakanak and Dillingham.',
 'AK96': 'Data represent information from nearest incorporated place (Dillingham city), which includes Kanakanak and Dillingham.',
 'AK97': 'Data represent information from nearest incorporated place (Diomede city), which includes Diomede.',
 'AK98': 'Data represent information from nearest census designated place (Dot Lake CDP), which includes Dot Lake.',
 'AK503': 'Data represent information from nearest census designated place (Dot Lake Village CDP), which includes Dot Lake Village.',
 'AK100': 'Data represent information from nearest census designated place (Dry Creek CDP), which includes Dry Creek.',
 'AK102': 'Data represent information from nearest incorporated place (Eagle city), which includes Eagle.',
 'AK104': 'Data represent information from nearest census designated place (Eagle Village CDP), which includes Eagle Village.',
 'AK105': 'Data represent information from nearest incorporated place (Edna Bay city), which includes Edna Bay.',
 'AK106': 'Data represent information from nearest incorporated place (Eek city), which includes Eek.',
 'AK108': 'Data represent information from nearest incorporated place (Egegik city), which includes Egegik.',
 'AK442': 'Data represent information from nearest census designated place (Eielson AFB CDP), which includes Eielson Air Force Base.',
 'AK112': 'Data represent information from nearest incorporated place (Ekwok city), which includes Ekwok.',
 'AK115': 'Data represent information from nearest incorporated place (Elim city), which includes Elim.',
 'AK117': 'Data represent information from nearest incorporated place (Emmonak city), which includes Emmonak and Kwiguk.',
 'AK219': 'Data represent information from nearest incorporated place (Emmonak city), which includes Emmonak and Kwiguk.',
 'AK120': 'Data represent information from nearest census designated place (Ester CDP), which includes Ester.',
 'AK504': 'Data represent information from nearest census designated place (Eureka Roadhouse CDP), which includes Eureka Roadhouse.',
 'AK505': 'Data represent information from nearest census designated place (Evansville CDP), which includes Evansville.',
 'AK122': 'Data represent information from nearest census designated place (Excursion Inlet CDP), which includes Excursion Inlet.',
 'AK125': 'Data represent information from nearest incorporated place (False Pass city), which includes False Pass, Ikatan, and Morzhovoi.',
 'AK163': 'Data represent information from nearest incorporated place (False Pass city), which includes False Pass, Ikatan, and Morzhovoi.',
 'AK252': 'Data represent information from nearest incorporated place (False Pass city), which includes False Pass, Ikatan, and Morzhovoi.',
 'AK507': 'Data represent information from nearest census designated place (Farmers Loop CDP), which includes Farmers Loop.',
 'AK506': 'Data represent information from nearest census designated place (Farm Loop CDP), which includes Farm Loop.',
 'AK126': 'Data represent information from nearest census designated place (Ferry CDP), which includes Ferry.',
 'AK508': 'Data represent information from nearest census designated place (Fishhook CDP), which includes Fishhook.',
 'AK128': 'Data represent information from nearest census designated place (Flat CDP), which includes Flat and Iditarod.',
 'AK161': 'Data represent information from nearest census designated place (Flat CDP), which includes Flat and Iditarod.',
 'AK440': 'Data represent information from nearest census designated place (Fort Greely CDP), which includes Fort Greely.',
 'AK130': 'Data represent information from nearest incorporated place (Fort Yukon city), which includes Fort Yukon.',
 'AK509': 'Data represent information from nearest census designated place (Four Mile Road CDP), which includes Four Mile Road.',
 'AK131': 'Data represent information from nearest census designated place (Fox CDP), which includes Fox.',
 'AK510': 'Data represent information from nearest census designated place (Fox River CDP), which includes Fox River.',
 'AK511': 'Data represent information from nearest census designated place (Fritz Creek CDP), which includes Fritz Creek.',
 'AK512': 'Data represent information from nearest census designated place (Funny River CDP), which includes Funny River.',
 'AK132': 'Data represent information from nearest census designated place (Gakona CDP), which includes Gakona.',
 'AK133': 'Data represent information from nearest incorporated place (Galena city), which includes Galena.',
 'AK513': 'Data represent information from nearest census designated place (Game Creek CDP), which includes Game Creek.',
 'AK239': 'Data represent information from nearest census designated place (Gateway CDP), which includes Matanuska and Gateway.',
 'AK514': 'Data represent information from nearest census designated place (Gateway CDP), which includes Matanuska and Gateway.',
 'AK515': 'Data represent information from nearest census designated place (Glacier View CDP), which includes Glacier View.',
 'AK137': 'Data represent information from nearest census designated place (Glennallen CDP), which includes Glennallen.',
 'AK516': 'Data represent information from nearest census designated place (Goldstream CDP), which includes Goldstream.',
 'AK138': 'Data represent information from nearest incorporated place (Golovin city), which includes Golovin.',
 'AK139': 'Data represent information from nearest incorporated place (Goodnews Bay city), which includes Goodnews Bay.',
 'AK140': 'Data represent information from nearest incorporated place (Grayling city), which includes Grayling.',
 'AK141': 'Data represent information from nearest census designated place (Gulkana CDP), which includes Gulkana.',
 'AK142': 'Data represent information from nearest incorporated place (Gustavus city), which includes Gustavus.',
 'AK143': 'Data represent information from nearest census designated place (Haines CDP), which includes Haines.',
 'AK517': 'Data represent information from nearest census designated place (Halibut Cove CDP), which includes Halibut Cove.',
 'AK518': 'Data represent information from nearest census designated place (Happy Valley CDP), which includes Happy Valley.',
 'AK519': 'Data represent information from nearest census designated place (Harding-Birch Lakes CDP), which includes Harding-Birch Lakes.',
 'AK146': 'Data represent information from nearest census designated place (Healy CDP), which includes Healy and Suntrana.',
 'AK378': 'Data represent information from nearest census designated place (Healy CDP), which includes Healy and Suntrana.',
 'AK147': 'Data represent information from nearest census designated place (Healy Lake CDP), which includes Healy Lake.',
 'AK520': 'Data represent information from nearest census designated place (Hobart Bay CDP), which includes Hobart Bay.',
 'AK150': 'Data represent information from nearest census designated place (Hollis CDP), which includes Hollis.',
 'AK151': 'Data represent information from nearest incorporated place (Holy Cross city), which includes Holy Cross.',
 'AK152': 'Data represent information from nearest incorporated place (Homer city), which includes Homer.',
 'AK153': 'Data represent information from nearest incorporated place (Hoonah city), which includes Hoonah.',
 'AK154': 'Data represent information from nearest incorporated place (Hooper Bay city), which includes Hooper Bay.',
 'AK155': 'Data represent information from nearest census designated place (Hope CDP), which includes Hope.',
 'AK156': 'Data represent information from nearest incorporated place (Houston city), which includes Houston.',
 'AK157': 'Data represent information from nearest incorporated place (Hughes city), which includes Hughes.',
 'AK158': 'Data represent information from nearest incorporated place (Huslia city), which includes Huslia.',
 'AK159': 'Data represent information from nearest incorporated place (Hydaburg city), which includes Hydaburg.',
 'AK160': 'Data represent information from nearest census designated place (Hyder CDP), which includes Hyder.',
 'AK162': 'Data represent information from nearest census designated place (Igiugig CDP), which includes Igiugig.',
 'AK164': 'Data represent information from nearest census designated place (Iliamna CDP), which includes Iliamna.',
 'AK169': 'Data represent information from nearest census designated place (Ivanof Bay CDP), which includes Ivanof Bay.',
 'AK173': 'Data represent information from nearest incorporated place (Kachemak city), which includes Kachemak.',
 'AK174': 'Data represent information from nearest incorporated place (Kake city), which includes Kake.',
 'AK176': 'Data represent information from nearest incorporated place (Kaktovik city), which includes Kaktovik.',
 'AK177': 'Data represent information from nearest census designated place (Kalifornsky CDP), which includes Kalifornsky.',
 'AK179': 'Data represent information from nearest incorporated place (Kaltag city), which includes Kaltag.',
 'AK181': 'Data represent information from nearest census designated place (Karluk CDP), which includes Karluk.',
 'AK182': 'Data represent information from nearest incorporated place (Kasaan city), which includes Kasaan.',
 'AK185': 'Data represent information from nearest census designated place (Kasigluk CDP), which includes Kasigluk.',
 'AK186': 'Data represent information from nearest census designated place (Kasilof CDP), which includes Kasilof.',
 'AK188': 'Data represent information from nearest incorporated place (Kenai city), which includes Kenai.',
 'AK189': 'Data represent information from nearest census designated place (Kenny Lake CDP), which includes Kenny Lake and Lower Tonsina.',
 'AK232': 'Data represent information from nearest census designated place (Kenny Lake CDP), which includes Kenny Lake and Lower Tonsina.',
 'AK191': 'Data represent information from nearest incorporated place (Ketchikan city), which includes Ketchikan.',
 'AK192': 'Data represent information from nearest incorporated place (Kiana city), which includes Kiana.',
 'AK196': 'Data represent information from nearest census designated place (King Salmon CDP), which includes King Salmon.',
 'AK197': 'Data represent information from nearest census designated place (Kipnuk CDP), which includes Kipnuk.',
 'AK198': 'Data represent information from nearest incorporated place (Kivalina city), which includes Kivalina.',
 'AK202': 'Data represent information from nearest census designated place (Klukwan CDP), which includes Klukwan.',
 'AK203': 'Data represent information from nearest census designated place (Knik-Fairview CDP), which includes Knik.',
 'AK521': 'Data represent information from nearest census designated place (Knik River CDP), which includes Knik River.',
 'AK204': 'Data represent information from nearest incorporated place (Kobuk city), which includes Kobuk.',
 'AK205': 'Data represent information from nearest incorporated place (Kodiak city), which includes Kodiak.',
 'AK522': 'Data represent information from nearest census designated place (Kodiak Station CDP), which includes Kodiak Station.',
 'AK206': 'Data represent information from nearest census designated place (Kokhanok CDP), which includes Kokhanok.',
 'AK208': 'Data represent information from nearest census designated place (Koliganek CDP), which includes Koliganek.',
 'AK209': 'Data represent information from nearest census designated place (Kongiganak CDP), which includes Kongiganak.',
 'AK210': 'Data represent information from nearest incorporated place (Kotlik city), which includes Kotlik.',
 'AK211': 'Data represent information from nearest incorporated place (Kotzebue city), which includes Kotzebue.',
 'AK212': 'Data represent information from nearest incorporated place (Koyuk city), which includes Koyuk.',
 'AK213': 'Data represent information from nearest incorporated place (Koyukuk city), which includes Koyukuk.',
 'AK214': 'Data represent information from nearest incorporated place (Kupreanof city), which includes Kupreanof.',
 'AK217': 'Data represent information from nearest incorporated place (Kwethluk city), which includes Kwethluk.',
 'AK218': 'Data represent information from nearest census designated place (Kwigillingok CDP), which includes Kwigillingok.',
 'AK523': 'Data represent information from nearest census designated place (Lake Louise CDP), which includes Lake Louise.',
 'AK220': 'Data represent information from nearest census designated place (Lake Minchumina CDP), which includes Lake Minchumina.',
 'AK221': 'Data represent information from nearest incorporated place (Larsen Bay city), which includes Larsen Bay.',
 'AK524': 'Data represent information from nearest census designated place (Lazy Mountain CDP), which includes Lazy Mountain.',
 'AK226': 'Data represent information from nearest census designated place (Levelock CDP), which includes Levelock.',
 'AK228': 'Data represent information from nearest census designated place (Lime Village CDP), which includes Lime Village.',
 'AK229': 'Data represent information from nearest census designated place (Livengood CDP), which includes Livengood.',
 'AK230': 'Data represent information from nearest census designated place (Loring CDP), which includes Loring.',
 'AK525': 'Data represent information from nearest census designated place (Lowell Point CDP), which includes Lowell Point.',
 'AK231': 'Data represent information from nearest incorporated place (Lower Kalskag city), which includes Lower Kalskag.',
 'AK526': 'Data represent information from nearest census designated place (Lutak CDP), which includes Lutak.',
 'AK240': 'Data represent information from nearest census designated place (McCarthy CDP), which includes McCarthy.',
 'AK241': 'Data represent information from nearest incorporated place (McGrath city), which includes McGrath.',
 'AK234': 'Data represent information from nearest census designated place (Manley Hot Springs CDP), which includes Manley Hot Springs.',
 'AK235': 'Data represent information from nearest incorporated place (Manokotak city), which includes Manokotak.',
 'AK237': 'Data represent information from nearest incorporated place (Marshall city), which includes Marshall.',
 'AK527': 'Data represent information from nearest census designated place (Meadow Lakes CDP), which includes Meadow Lakes.',
 'AK245': 'Data represent information from nearest incorporated place (Mekoryuk city), which includes Mekoryuk.',
 'AK246': 'Data represent information from nearest census designated place (Mendeltna CDP), which includes Mendeltna.',
 'AK247': 'Data represent information from nearest census designated place (Mentasta Lake CDP), which includes Mentasta Lake.',
 'AK528': 'Data represent information from nearest census designated place (Mertarvik CDP), which includes Mertarvik.',
 'AK529': 'Data represent information from nearest census designated place (Mill Bay CDP), which includes Mill Bay.',
 'AK250': 'Data represent information from nearest census designated place (Minto CDP), which includes Minto.',
 'AK530': 'Data represent information from nearest census designated place (Moose Creek CDP), which includes Moose Creek.',
 'AK251': 'Data represent information from nearest census designated place (Moose Pass CDP), which includes Moose Pass.',
 'AK531': 'Data represent information from nearest census designated place (Mosquito Lake CDP), which includes Mosquito Lake.',
 'AK254': 'Data represent information from nearest incorporated place (Mountain Village city), which includes Mountain Village.',
 'AK532': 'Data represent information from nearest census designated place (Mud Bay CDP), which includes Mud Bay.',
 'AK256': 'Data represent information from nearest census designated place (Nabesna CDP), which includes Nabesna.',
 'AK227': 'Data represent information from nearest census designated place (Naknek CDP), which includes Libbyville and Naknek.',
 'AK258': 'Data represent information from nearest census designated place (Naknek CDP), which includes Libbyville and Naknek.',
 'AK259': 'Data represent information from nearest census designated place (Nanwalek CDP), which includes Nanwalek.',
 'AK261': 'Data represent information from nearest incorporated place (Napakiak city), which includes Napakiak.',
 'AK263': 'Data represent information from nearest incorporated place (Napaskiak city), which includes Napaskiak.',
 'AK533': 'Data represent information from nearest census designated place (Naukati Bay CDP), which includes Naukati Bay.',
 'AK265': 'Data represent information from nearest census designated place (Nelchina CDP), which includes Nelchina.',
 'AK266': 'Data represent information from nearest census designated place (Nelson Lagoon CDP), which includes Nelson Lagoon.',
 'AK267': 'Data represent information from nearest incorporated place (Nenana city), which includes Nenana.',
 'AK270': 'Data represent information from nearest incorporated place (Newhalen city), which includes Newhalen.',
 'AK269': 'Data represent information from nearest incorporated place (New Stuyahok city), which includes New Stuyahok.',
 'AK271': 'Data represent information from nearest census designated place (Newtok CDP), which includes Newtok.',
 'AK272': 'Data represent information from nearest incorporated place (Nightmute city), which includes Nightmute.',
 'AK273': 'Data represent information from nearest census designated place (Nikiski CDP), which includes Nikiski.',
 'AK274': 'Data represent information from nearest census designated place (Nikolaevsk CDP), which includes Nikolaevsk.',
 'AK275': 'Data represent information from nearest incorporated place (Nikolai city), which includes Nikolai.',
 'AK276': 'Data represent information from nearest census designated place (Nikolski CDP), which includes Nikolski.',
 'AK278': 'Data represent information from nearest census designated place (Ninilchik CDP), which includes Ninilchik.',
 'AK279': 'Data represent information from nearest census designated place (Noatak CDP), which includes Noatak.',
 'AK280': 'Data represent information from nearest incorporated place (Nome city), which includes Nome.',
 'AK281': 'Data represent information from nearest incorporated place (Nondalton city), which includes Nondalton.',
 'AK282': 'Data represent information from nearest incorporated place (Noorvik city), which includes Noorvik.',
 'AK534': 'Data represent information from nearest census designated place (North Lakes CDP), which includes North Lakes.',
 'AK148': 'Data represent information from nearest incorporated place (North Pole city), which includes Highland Park and North Pole.',
 'AK283': 'Data represent information from nearest incorporated place (North Pole city), which includes Highland Park and North Pole.',
 'AK187': 'Data represent information from nearest census designated place (Northway CDP), which includes Kathakne, Northway, Northway Indian Village, and Northway Junction.',
 'AK284': 'Data represent information from nearest census designated place (Northway CDP), which includes Kathakne, Northway, Northway Indian Village, and Northway Junction.',
 'AK285': 'Data represent information from nearest census designated place (Northway CDP), which includes Kathakne, Northway, Northway Indian Village, and Northway Junction.',
 'AK286': 'Data represent information from nearest census designated place (Northway CDP), which includes Kathakne, Northway, Northway Indian Village, and Northway Junction.',
 'AK287': 'Data represent information from nearest incorporated place (Nuiqsut city), which includes Nuiqsut.',
 'AK288': 'Data represent information from nearest incorporated place (Nulato city), which includes Nulato.',
 'AK289': 'Data represent information from nearest incorporated place (Nunam Iqua city), which includes Nunam Iqua.',
 'AK290': 'Data represent information from nearest incorporated place (Nunapitchuk city), which includes Nunapitchuk.',
 'AK293': 'Data represent information from nearest incorporated place (Old Harbor city), which includes Old Harbor.',
 'AK296': 'Data represent information from nearest census designated place (Oscarville CDP), which includes Oscarville.',
 'AK298': 'Data represent information from nearest incorporated place (Ouzinkie city), which includes Ouzinkie.',
 'AK300': 'Data represent information from nearest incorporated place (Palmer city), which includes Palmer.',
 'AK303': 'Data represent information from nearest census designated place (Paxson CDP), which includes Paxson.',
 'AK304': 'Data represent information from nearest census designated place (Pedro Bay CDP), which includes Pedro Bay.',
 'AK305': 'Data represent information from nearest incorporated place (Pelican city), which includes Pelican.',
 'AK307': 'Data represent information from nearest census designated place (Perryville CDP), which includes Perryville.',
 'AK308': 'Data represent information from nearest census designated place (Petersburg CDP), which includes Petersburg.',
 'AK309': 'Data represent information from nearest census designated place (Petersville CDP), which includes Petersville.',
 'AK311': 'Data represent information from nearest incorporated place (Pilot Point city), which includes Pilot Point.',
 'AK312': 'Data represent information from nearest incorporated place (Pilot Station city), which includes Pilot Station.',
 'AK313': 'Data represent information from nearest census designated place (Pitkas Point CDP), which includes Pitkas Point.',
 'AK314': 'Data represent information from nearest incorporated place (Platinum city), which includes Platinum.',
 'AK535': 'Data represent information from nearest census designated place (Pleasant Valley CDP), which includes Pleasant Valley.',
 'AK315': 'Data represent information from nearest census designated place (Point Baker CDP), which includes Point Baker.',
 'AK316': 'Data represent information from nearest incorporated place (Point Hope city), which includes Point Hope.',
 'AK317': 'Data represent information from nearest census designated place (Point Lay CDP), which includes Point Lay.',
 'AK536': 'Data represent information from nearest census designated place (Point MacKenzie CDP), which includes Point MacKenzie.',
 'AK537': 'Data represent information from nearest census designated place (Point Possession CDP), which includes Point Possession.',
 'AK538': 'Data represent information from nearest census designated place (Pope-Vannoy Landing CDP), which includes Pope-Vannoy Landing.',
 'AK329': 'Data represent information from nearest census designated place (Portage Creek CDP), which includes Portage Creek.',
 'AK319': 'Data represent information from nearest incorporated place (Port Alexander city), which includes Port Alexander.',
 'AK320': 'Data represent information from nearest census designated place (Port Alsworth CDP), which includes Port Alsworth.',
 'AK539': 'Data represent information from nearest census designated place (Port Clarence CDP), which includes Port Clarence.',
 'AK322': 'Data represent information from nearest census designated place (Port Graham CDP), which includes Port Graham.',
 'AK323': 'Data represent information from nearest incorporated place (Port Heiden city), which includes Port Heiden.',
 'AK324': 'Data represent information from nearest incorporated place (Port Lions city), which includes Port Lions.',
 'AK540': 'Data represent information from nearest census designated place (Primrose CDP), which includes Primrose.',
 'AK331': 'Data represent information from nearest census designated place (Prudhoe Bay CDP), which includes Prudhoe Bay and Deadhorse.',
 'AK93': 'Data represent information from nearest census designated place (Prudhoe Bay CDP), which includes Prudhoe Bay and Deadhorse.',
 'AK332': 'Data represent information from nearest incorporated place (Quinhagak city), which includes Quinhagak.',
 'AK334': 'Data represent information from nearest census designated place (Rampart CDP), which includes Rampart.',
 'AK335': 'Data represent information from nearest census designated place (Red Devil CDP), which includes Red Devil.',
 'AK541': 'Data represent information from nearest census designated place (Red Dog Mine CDP), which includes Red Dog Mine.',
 'AK542': 'Data represent information from nearest census designated place (Ridgeway CDP), which includes Ridgeway.',
 'AK337': 'Data represent information from nearest incorporated place (Ruby city), which includes Ruby.',
 'AK338': 'Data represent information from nearest incorporated place (Russian Mission city), which includes Russian Mission.',
 'AK547': 'Data represent information from nearest incorporated place (St. George city), which includes St. George.',
 'AK340': "Data represent information from nearest incorporated place (St. Mary's city), which includes Saint Mary's.",
 'AK341': 'Data represent information from nearest incorporated place (St. Michael city), which includes Saint Michael.',
 'AK342': 'Data represent information from nearest incorporated place (St. Paul city), which includes Saint Paul.',
 'AK343': 'Data represent information from nearest census designated place (Salamatof CDP), which includes Salamatof.',
 'AK344': 'Data represent information from nearest census designated place (Salcha CDP), which includes Salcha.',
 'AK347': 'Data represent information from nearest incorporated place (Sand Point city), which includes Sand Point.',
 'AK349': 'Data represent information from nearest incorporated place (Savoonga city), which includes Savoonga.',
 'AK350': 'Data represent information from nearest incorporated place (Saxman city), which includes Saxman.',
 'AK351': 'Data represent information from nearest incorporated place (Scammon Bay city), which includes Scammon Bay.',
 'AK352': 'Data represent information from nearest incorporated place (Selawik city), which includes Selawik.',
 'AK353': 'Data represent information from nearest incorporated place (Seldovia city), which includes Seldovia.',
 'AK543': 'Data represent information from nearest census designated place (Seldovia Village CDP), which includes Seldovia Village.',
 'AK354': 'Data represent information from nearest incorporated place (Seward city), which includes Seward.',
 'AK355': 'Data represent information from nearest incorporated place (Shageluk city), which includes Shageluk.',
 'AK356': 'Data represent information from nearest incorporated place (Shaktoolik city), which includes Shaktoolik.',
 'AK358': 'Data represent information from nearest incorporated place (Shishmaref city), which includes Shishmaref.',
 'AK359': 'Data represent information from nearest incorporated place (Shungnak city), which includes Shungnak.',
 'AK544': 'Data represent information from nearest census designated place (Silver Springs CDP), which includes Silver Springs.',
 'AK361': 'Data represent information from nearest census designated place (Skagway CDP), which includes Skagway.',
 'AK362': 'Data represent information from nearest census designated place (Skwentna CDP), which includes Skwentna.',
 'AK363': 'Data represent information from nearest census designated place (Slana CDP), which includes Slana.',
 'AK365': 'Data represent information from nearest census designated place (Sleetmute CDP), which includes Sleetmute.',
 'AK366': 'Data represent information from nearest incorporated place (Soldotna city), which includes Soldotna.',
 'AK545': 'Data represent information from nearest census designated place (South Lakes CDP), which includes South Lakes.',
 'AK368': 'Data represent information from nearest census designated place (South Naknek CDP), which includes South Naknek.',
 'AK546': 'Data represent information from nearest census designated place (South Van Horn CDP), which includes South Van Horn.',
 'AK372': 'Data represent information from nearest incorporated place (Stebbins city), which includes Stebbins.',
 'AK548': 'Data represent information from nearest census designated place (Steele Creek CDP), which includes Steele Creek.',
 'AK373': 'Data represent information from nearest census designated place (Sterling CDP), which includes Sterling.',
 'AK374': 'Data represent information from nearest census designated place (Stevens Village CDP), which includes Stevens Village.',
 'AK375': 'Data represent information from nearest census designated place (Stony River CDP), which includes Stony River.',
 'AK377': 'Data represent information from nearest census designated place (Sunrise CDP), which includes Sunrise.',
 'AK10': 'Data represent information from nearest census designated place (Susitna CDP), which includes Alexander Creek, Susitna Station, and Susitna.',
 'AK379': 'Data represent information from nearest census designated place (Susitna CDP), which includes Alexander Creek, Susitna Station, and Susitna.',
 'AK487': 'Data represent information from nearest census designated place (Susitna CDP), which includes Alexander Creek, Susitna Station, and Susitna.',
 'AK549': 'Data represent information from nearest census designated place (Susitna North CDP), which includes Susitna North.',
 'AK119': 'Data represent information from nearest census designated place (Sutton-Alpine CDP), which includes Eska, Jonesville, Sutton, and Sutton-Alpine.',
 'AK171': 'Data represent information from nearest census designated place (Sutton-Alpine CDP), which includes Eska, Jonesville, Sutton, and Sutton-Alpine.',
 'AK380': 'Data represent information from nearest census designated place (Sutton-Alpine CDP), which includes Eska, Jonesville, Sutton, and Sutton-Alpine.',
 'AK550': 'Data represent information from nearest census designated place (Sutton-Alpine CDP), which includes Eska, Jonesville, Sutton, and Sutton-Alpine.',
 'AK381': 'Data represent information from nearest census designated place (Takotna CDP), which includes Takotna.',
 'AK382': 'Data represent information from nearest census designated place (Talkeetna CDP), which includes Talkeetna.',
 'AK383': 'Data represent information from nearest census designated place (Tanacross CDP), which includes Tanacross.',
 'AK551': 'Data represent information from nearest census designated place (Tanaina CDP), which includes Tanaina.',
 'AK384': 'Data represent information from nearest incorporated place (Tanana city), which includes Tanana.',
 'AK116': 'Data represent information from nearest census designated place (Tatitlek CDP), which includes Ellamar and Tatitlek.',
 'AK386': 'Data represent information from nearest census designated place (Tatitlek CDP), which includes Ellamar and Tatitlek.',
 'AK387': 'Data represent information from nearest census designated place (Tazlina CDP), which includes Tazlina.',
 'AK390': 'Data represent information from nearest incorporated place (Teller city), which includes Teller.',
 'AK392': 'Data represent information from nearest incorporated place (Tenakee Springs city), which includes Tenakee Springs.',
 'AK393': 'Data represent information from nearest census designated place (Tetlin CDP), which includes Tetlin.',
 'AK396': 'Data represent information from nearest incorporated place (Thorne Bay city), which includes Thorne Bay.',
 'AK398': 'Data represent information from nearest incorporated place (Togiak city), which includes Togiak.',
 'AK399': 'Data represent information from nearest census designated place (Tok CDP), which includes Tok.',
 'AK401': 'Data represent information from nearest incorporated place (Toksook Bay city), which includes Toksook Bay and Umkumiute.',
 'AK412': 'Data represent information from nearest incorporated place (Toksook Bay city), which includes Toksook Bay and Umkumiute.',
 'AK552': 'Data represent information from nearest census designated place (Tolsona CDP), which includes Tolsona.',
 'AK403': 'Data represent information from nearest census designated place (Tonsina CDP), which includes Tonsina.',
 'AK553': 'Data represent information from nearest census designated place (Trapper Creek CDP), which includes Trapper Creek.',
 'AK404': 'Data represent information from nearest census designated place (Tuluksak CDP), which includes Tuluksak.',
 'AK405': 'Data represent information from nearest census designated place (Tuntutuliak CDP), which includes Tuntutuliak.',
 'AK277': 'Data represent information from nearest census designated place (Tununak CDP), which includes Nilikluguk and Tununak.',
 'AK406': 'Data represent information from nearest census designated place (Tununak CDP), which includes Nilikluguk and Tununak.',
 'AK407': 'Data represent information from nearest census designated place (Twin Hills CDP), which includes Twin Hills.',
 'AK436': 'Data represent information from nearest census designated place (Two Rivers CDP), which includes Two Rivers.',
 'AK408': 'Data represent information from nearest census designated place (Tyonek CDP), which includes Tyonek.',
 'AK409': 'Data represent information from nearest census designated place (Ugashik CDP), which includes Ugashik.',
 'AK414': 'Data represent information from nearest incorporated place (Unalakleet city), which includes Unalakleet.',
 'AK415': 'Data represent information from nearest incorporated place (Unalaska city), which includes Unalaska.',
 'AK178': 'Data represent information from nearest incorporated place (Upper Kalskag city), which includes Upper Kalskag.',
 'AK418': 'Data represent information from nearest incorporated place (Utqiag?vik city), which includes Utqiaġvik.',
 'AK421': 'Data represent information from nearest incorporated place (Valdez city), which includes Valdez.',
 'AK422': 'Data represent information from nearest census designated place (Venetie CDP), which includes Venetie.',
 'AK423': 'Data represent information from nearest incorporated place (Wainwright city), which includes Wainwright.',
 'AK424': 'Data represent information from nearest incorporated place (Wales city), which includes Wales.',
 'AK426': 'Data represent information from nearest incorporated place (Wasilla city), which includes Wasilla.',
 'AK427': 'Data represent information from nearest incorporated place (Whale Pass city), which includes Whale Pass.',
 'AK428': 'Data represent information from nearest incorporated place (White Mountain city), which includes White Mountain.',
 'AK554': 'Data represent information from nearest census designated place (Whitestone CDP), which includes Whitestone.',
 'AK555': 'Data represent information from nearest census designated place (Whitestone Logging Camp CDP), which includes Whitestone Logging Camp.',
 'AK429': 'Data represent information from nearest incorporated place (Whittier city), which includes Whittier.',
 'AK233': 'Data represent information from nearest census designated place (Willow CDP), which includes Lucky Shot Landing and Willow.',
 'AK430': 'Data represent information from nearest census designated place (Willow CDP), which includes Lucky Shot Landing and Willow.',
 'AK556': 'Data represent information from nearest census designated place (Willow Creek CDP), which includes Willow Creek.',
 'AK431': 'Data represent information from nearest census designated place (Wiseman CDP), which includes Wiseman.',
 'AK432': 'Data represent information from nearest census designated place (Womens Bay CDP), which includes Womens Bay.',
 'AK435': 'Data represent information from nearest census designated place (Yakutat CDP), which includes Yakutat.'}